/* Auto-generated C header for Summon FFI */

#ifndef SUMMON_FFI_H
#define SUMMON_FFI_H

#pragma once

/* Warning: This file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct ActionManagerHandle ActionManagerHandle;

typedef struct CalculatorHandle CalculatorHandle;

typedef struct SearchEngineHandle SearchEngineHandle;

typedef struct SnippetMatcherHandle SnippetMatcherHandle;

typedef struct CSearchResult {
  char *id;
  char *name;
  char *path;
  int64_t score;
} CSearchResult;

typedef struct CStringArray {
  char **data;
  size_t len;
} CStringArray;

typedef struct CIndexedApp {
  char *name;
  char *path;
} CIndexedApp;

typedef struct CClipboardEntry {
  char *content;
  double timestamp;
  uint8_t item_type;
  char *image_file_path;
  double image_width;
  double image_height;
  int32_t size;
  char *source_app;
} CClipboardEntry;

typedef struct CSnippetMatch {
  char *trigger;
  char *content;
} CSnippetMatch;

typedef struct CSnippet {
  char *id;
  char *trigger;
  char *content;
  bool enabled;
  char *category;
} CSnippet;

typedef struct CAppEntry {
  char *name;
  char *path;
} CAppEntry;

typedef struct CAppSettings {
  char *theme;
  char *custom_font_name;
  char *font_size;
  int32_t max_results;
  int32_t max_clipboard_items;
  int32_t clipboard_retention_days;
  char *quick_select_modifier;
  bool enable_commands;
  bool show_tray_icon;
  bool show_dock_icon;
  bool hide_traffic_lights;
} CAppSettings;

typedef struct CActionResult {
  char *id;
  char *title;
  char *subtitle;
  char *icon;
  char *url;
  float score;
} CActionResult;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct SearchEngineHandle *search_engine_new(void);

void search_engine_free(struct SearchEngineHandle *Handle);

bool search_engine_add_item(struct SearchEngineHandle *Handle,
                            const char *Id,
                            const char *Name,
                            const char *Path,
                            uint8_t ItemType);

struct CSearchResult *search_engine_search(struct SearchEngineHandle *Handle,
                                           const char *Query,
                                           size_t Limit,
                                           size_t *OutCount);

void search_results_free(struct CSearchResult *Results,
                         size_t Count);

bool search_engine_stats(struct SearchEngineHandle *Handle,
                         size_t *Total,
                         size_t *Apps,
                         size_t *Files,
                         size_t *Snippets);

size_t search_engine_scan_apps(struct SearchEngineHandle *Handle,
                               struct CStringArray Directories,
                               struct CStringArray ExcludePatterns);

struct CIndexedApp *search_engine_get_apps(struct SearchEngineHandle *Handle,
                                           size_t *OutCount);

void indexed_apps_free(struct CIndexedApp *Entries,
                       size_t Count);

bool search_engine_enable_file_search(struct SearchEngineHandle *Handle,
                                      struct CStringArray Directories,
                                      struct CStringArray Extensions);

bool search_engine_disable_file_search(struct SearchEngineHandle *Handle);

struct CalculatorHandle *calculator_new(void);

void calculator_free(struct CalculatorHandle *Handle);

char *calculator_evaluate(struct CalculatorHandle *Handle,
                          const char *Expr);

char *calculator_get_history_json(struct CalculatorHandle *Handle);

void calculator_free_string(char *S);

void calculator_clear_history(struct CalculatorHandle *Handle);

bool clipboard_storage_add_text(ClipboardStorageHandle *Handle,
                                const char *Content,
                                double Timestamp,
                                int32_t Size,
                                const char *SourceApp);

bool clipboard_storage_add_image(ClipboardStorageHandle *Handle,
                                 const char *Content,
                                 double Timestamp,
                                 const char *ImageFilePath,
                                 double Width,
                                 double Height,
                                 int32_t Size,
                                 const char *SourceApp);

struct CClipboardEntry *clipboard_storage_get_entries(ClipboardStorageHandle *Handle,
                                                      size_t Start,
                                                      size_t Count,
                                                      size_t *OutCount);

void clipboard_entries_free(struct CClipboardEntry *Entries,
                            size_t Count);

size_t clipboard_storage_len(ClipboardStorageHandle *Handle);

bool clipboard_storage_trim(ClipboardStorageHandle *Handle,
                            size_t Max);

bool clipboard_storage_clear(ClipboardStorageHandle *Handle);

bool clipboard_storage_remove_at(ClipboardStorageHandle *Handle,
                                 size_t Index);

struct SnippetMatcherHandle *snippet_matcher_new(void);

void snippet_matcher_free(struct SnippetMatcherHandle *Handle);

bool snippet_matcher_update(struct SnippetMatcherHandle *Handle,
                            const char *Json);

struct CSnippetMatch *snippet_matcher_find(struct SnippetMatcherHandle *Handle,
                                           const char *Text);

void snippet_match_free(struct CSnippetMatch *Result);

bool snippet_storage_add(SnippetStorageHandle *Handle,
                         const char *Id,
                         const char *Trigger,
                         const char *Content,
                         bool Enabled,
                         const char *Category);

bool snippet_storage_update(SnippetStorageHandle *Handle,
                            const char *Id,
                            const char *Trigger,
                            const char *Content,
                            bool Enabled,
                            const char *Category);

bool snippet_storage_delete(SnippetStorageHandle *Handle,
                            const char *Id);

struct CSnippet *snippet_storage_get_all(SnippetStorageHandle *Handle,
                                         size_t *OutCount);

struct CSnippet *snippet_storage_get_enabled(SnippetStorageHandle *Handle,
                                             size_t *OutCount);

void snippets_free(struct CSnippet *Snippets,
                   size_t Count);

size_t snippet_storage_len(SnippetStorageHandle *Handle);

bool app_storage_add(AppStorageHandle *Handle,
                     const char *Name,
                     const char *Path);

struct CAppEntry *app_storage_get_all(AppStorageHandle *Handle,
                                      size_t *OutCount);

void app_entries_free(struct CAppEntry *Entries,
                      size_t Count);

size_t app_storage_len(AppStorageHandle *Handle);

bool app_storage_clear(AppStorageHandle *Handle);

struct CAppSettings *settings_storage_get(SettingsStorageHandle *Handle);

bool settings_storage_save(SettingsStorageHandle *Handle,
                           const char *Theme,
                           const char *CustomFontName,
                           const char *FontSize,
                           int32_t MaxResults,
                           int32_t MaxClipboardItems,
                           int32_t ClipboardRetentionDays,
                           const char *QuickSelectModifier,
                           bool EnableCommands,
                           bool ShowTrayIcon,
                           bool ShowDockIcon,
                           bool HideTrafficLights,
                           const char *SearchFoldersJson,
                           const char *LauncherShortcutJson,
                           const char *ClipboardShortcutJson);

void settings_free(struct CAppSettings *Settings);

char *settings_storage_get_search_folders(SettingsStorageHandle *Handle);

char *settings_storage_get_launcher_shortcut(SettingsStorageHandle *Handle);

char *settings_storage_get_clipboard_shortcut(SettingsStorageHandle *Handle);

struct ActionManagerHandle *action_manager_new(const char *Path);

void action_manager_free(struct ActionManagerHandle *Handle);

struct CActionResult *action_manager_search(struct ActionManagerHandle *Handle,
                                            const char *Query,
                                            size_t *OutCount);

void action_results_free(struct CActionResult *Results,
                         size_t Count);

bool action_manager_add_json(struct ActionManagerHandle *Handle,
                             const char *Json);

bool action_manager_add_quick_link(struct ActionManagerHandle *Handle,
                                   const char *Id,
                                   const char *Name,
                                   const char *Keyword,
                                   const char *Url,
                                   const char *Icon);

bool action_manager_add_pattern(struct ActionManagerHandle *Handle,
                                const char *Id,
                                const char *Name,
                                const char *Pattern,
                                const char *Url,
                                const char *Icon);

bool action_manager_update_json(struct ActionManagerHandle *Handle,
                                const char *Json);

bool action_manager_remove(struct ActionManagerHandle *Handle,
                           const char *Id);

bool action_manager_toggle(struct ActionManagerHandle *Handle,
                           const char *Id);

char *action_manager_get_all_json(struct ActionManagerHandle *Handle);

bool action_manager_import_defaults(struct ActionManagerHandle *Handle);

void string_free(char *S);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SUMMON_FFI_H */
