included:
  - src/swift

excluded:
  - .build
  - target
  - src/rust

opt_in_rules:
  - empty_count
  - explicit_init
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument

disabled_rules:
  - line_length  # Many SwiftUI views have long lines
  - trailing_comma  # Allow trailing commas in arrays/dicts
  - nesting  # SwiftUI views often nest deeply
  - large_tuple  # RGB color tuples are fine
  - multiple_closures_with_trailing_closure  # SwiftUI patterns
  - opening_brace  # Formatting handled by swiftformat

identifier_name:
  min_length: 1  # Allow single-character names (i, x, y)
  excluded:
    - id
    - db
    - x
    - y
    - z

function_body_length:
  warning: 120
  error: 200

type_body_length:
  warning: 600
  error: 800

file_length:
  warning: 1200
  error: 1600

cyclomatic_complexity:
  warning: 15
  error: 25

# Analyzer rules disabled - require full Xcode installation
# analyzer_rules:
#   - unused_declaration
#   - unused_import
