included:
    - src/swift

excluded:
    - .build
    - target
    - src/rust
    - src/swift/Wrappers/FFIBridge.swift

opt_in_rules:
    - array_init
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - empty_collection_literal
    - empty_count
    - empty_string
    - first_where
    - flatmap_over_map_reduce
    - last_where
    - reduce_into
    - sorted_first_last
    - unused_optional_binding
    - explicit_init
    - implicit_return
    - redundant_nil_coalescing
    - redundant_type_annotation
    - toggle_bool
    - unavailable_function
    - unneeded_parentheses_in_closure_argument
    - yoda_condition
    - closure_spacing
    - multiline_arguments
    - multiline_function_chains
    - multiline_parameters
    - operator_usage_whitespace
    - vertical_parameter_alignment_on_call

analyzer_rules:
    - explicit_self
    - unused_declaration

disabled_rules:
    - line_length
    - trailing_comma
    - nesting
    - large_tuple
    - multiple_closures_with_trailing_closure
    - opening_brace
    - blanket_disable_command
    - closure_parameter_position

identifier_name:
    min_length: 1
    excluded:
        - id
        - db
        - x
        - y
        - z
        - i
        - j
        - k

cyclomatic_complexity:
    warning: 12
    error: 20
    ignores_case_statements: true

function_body_length:
    warning: 80
    error: 120

type_body_length:
    warning: 400
    error: 600

file_length:
    warning: 600
    error: 900

function_parameter_count:
    warning: 5
    error: 7
    ignores_default_parameters: true

custom_rules:
    avoid_stateobject_in_child:
        name: "Avoid @StateObject in Child Views"
        regex: "struct \\w+View.*\\{[\\s\\S]*?@StateObject"
        message: "Use @ObservedObject in child views; @StateObject should only be in parent/owner views"
        severity: warning

    prefer_async_await:
        name: "Prefer async/await over completion handlers"
        regex: "\\(completion:.*@escaping"
        message: "Consider using async/await instead of completion handlers for Swift 6"
        severity: warning

    explicit_main_actor_ui:
        name: "UI classes should be @MainActor"
        regex: "class \\w+(?:View|Controller|Manager).*\\{(?![\\s\\S]*@MainActor)"
        message: "UI-related classes should be marked @MainActor in Swift 6"
        severity: warning
